stages:
  preprocess_data:
    cmd: python src/data/make_dataset.py data/raw/ data/interim/ data/processed/
    deps:
    - data/raw/
    outs:
    - data/interim/test_data.pkl
    - data/interim/train_data.pkl
    - data/interim/val_data.pkl
    - data/processed/train_target.pkl
    - data/processed/val_target.pkl
  build_features:
    cmd: python src/features/build_features.py data/interim/ data/processed/
    deps:
    - data/interim/test_data.pkl
    - data/interim/train_data.pkl
    - data/interim/val_data.pkl
    outs:
    - data/processed/test_data.pkl
    - data/processed/train_data.pkl
    - data/processed/val_data.pkl
  train_model:
    cmd: python src/models/train_model.py data/processed/train_data.pkl data/processed/train_target.pkl
      models/
    deps:
    - data/processed/train_data.pkl
    - data/processed/train_target.pkl
    outs:
    - models/model_fit.pkl
    - models/transformer.pkl
